CREATE SCHEMA parcel;
SET LOCAL search_path = parcel, public;

-- 1. 조직과 사용자
CREATE TABLE organizations (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       VARCHAR(40)  NOT NULL UNIQUE,
    name       VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

ALTER TABLE public.users ADD COLUMN organization_id BIGINT REFERENCES parcel.organizations(id);
INSERT INTO organizations(code, name)
SELECT DISTINCT 'legacy-user-' || COALESCE(manager_id,id), 'Imported organization ' || COALESCE(manager_id,id)
FROM public.users;
UPDATE public.users u SET organization_id = o.id FROM organizations o
WHERE o.code = 'legacy-user-' || COALESCE(u.manager_id,u.id);
ALTER TABLE public.users ALTER COLUMN organization_id SET NOT NULL;
ALTER TABLE public.users ADD CONSTRAINT uq_users_org_id UNIQUE (organization_id,id);

-- 2. 벨트와 장비
CREATE TABLE conveyor_belts (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id         BIGINT       NOT NULL REFERENCES organizations(id),
    code                    VARCHAR(40)  NOT NULL,
    name                    VARCHAR(100) NOT NULL,
    enabled                 BOOLEAN      NOT NULL DEFAULT TRUE,
    desired_rule_version_id BIGINT,
    desired_set_at          TIMESTAMPTZ,
    created_at              TIMESTAMPTZ  NOT NULL DEFAULT now(),

    UNIQUE (organization_id, code),
    UNIQUE (organization_id, id),
    CHECK (
        (desired_rule_version_id IS NULL AND desired_set_at IS NULL)
        OR
        (desired_rule_version_id IS NOT NULL AND desired_set_at IS NOT NULL)
    )
);

CREATE TABLE devices (
    id                      UUID PRIMARY KEY,
    organization_id         BIGINT       NOT NULL,
    belt_id                 BIGINT       NOT NULL,
    device_code             VARCHAR(80)  NOT NULL,
    credential_hash         VARCHAR(255) NOT NULL,
    active                  BOOLEAN      NOT NULL DEFAULT TRUE,
    credential_revoked      BOOLEAN      NOT NULL DEFAULT FALSE,
    applied_rule_version_id BIGINT,
    applied_at              TIMESTAMPTZ,
    last_seen_at            TIMESTAMPTZ,
    created_at              TIMESTAMPTZ  NOT NULL DEFAULT now(),

    UNIQUE (organization_id, device_code),
    UNIQUE (organization_id, belt_id, id),
    FOREIGN KEY (organization_id, belt_id)
        REFERENCES conveyor_belts (organization_id, id),
    CHECK (
        (applied_rule_version_id IS NULL AND applied_at IS NULL)
        OR
        (applied_rule_version_id IS NOT NULL AND applied_at IS NOT NULL)
    )
);

-- 무결성을 위한 UNIQUE 인덱스: 벨트당 활성 장비 최대 1대
CREATE UNIQUE INDEX uq_devices_one_active_per_belt
    ON devices (organization_id, belt_id)
    WHERE active = TRUE;

-- 물리 슈트. 동작 각도는 아래 version_chutes에 버전별로 저장한다.
CREATE TABLE chutes (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT      NOT NULL,
    belt_id         BIGINT      NOT NULL,
    code            VARCHAR(40) NOT NULL,
    name            VARCHAR(50) NOT NULL,
    enabled         BOOLEAN     NOT NULL DEFAULT TRUE,

    UNIQUE (organization_id, belt_id, code),
    UNIQUE (organization_id, belt_id, id),
    FOREIGN KEY (organization_id, belt_id)
        REFERENCES conveyor_belts (organization_id, id)
);

-- 3. 분류 그룹과 배포 설정
CREATE TABLE sorting_groups (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT       NOT NULL,
    belt_id         BIGINT       NOT NULL,
    name            VARCHAR(100) NOT NULL,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),

    UNIQUE (belt_id, name),
    UNIQUE (organization_id, belt_id, id),
    FOREIGN KEY (organization_id, belt_id)
        REFERENCES conveyor_belts (organization_id, id)
);

CREATE TABLE rule_versions (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id     BIGINT       NOT NULL,
    belt_id             BIGINT       NOT NULL,
    group_id            BIGINT       NOT NULL,
    group_name_snapshot VARCHAR(100) NOT NULL,
    version_no          INTEGER      NOT NULL CHECK (version_no > 0),
    status              VARCHAR(12)  NOT NULL DEFAULT 'DRAFT'
                        CHECK (status IN ('DRAFT', 'PUBLISHED')),
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    published_at        TIMESTAMPTZ,

    UNIQUE (group_id, version_no),
    UNIQUE (organization_id, belt_id, id),
    FOREIGN KEY (organization_id, belt_id, group_id)
        REFERENCES sorting_groups (organization_id, belt_id, id),
    CHECK (
        (status = 'DRAFT' AND published_at IS NULL)
        OR
        (status = 'PUBLISHED' AND published_at IS NOT NULL)
    )
);

-- 해당 버전을 배포했을 때의 슈트 이름과 서보 각도
CREATE TABLE version_chutes (
    organization_id     BIGINT      NOT NULL,
    belt_id             BIGINT      NOT NULL,
    version_id          BIGINT      NOT NULL,
    chute_id            BIGINT      NOT NULL,
    chute_name_snapshot VARCHAR(50) NOT NULL,
    servo_deg_snapshot  SMALLINT    NOT NULL
                        CHECK (servo_deg_snapshot BETWEEN 0 AND 180),

    PRIMARY KEY (organization_id, belt_id, version_id, chute_id),
    FOREIGN KEY (organization_id, belt_id, version_id)
        REFERENCES rule_versions (organization_id, belt_id, id),
    FOREIGN KEY (organization_id, belt_id, chute_id)
        REFERENCES chutes (organization_id, belt_id, id)
);

CREATE TABLE sorting_rules (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT       NOT NULL,
    belt_id         BIGINT       NOT NULL,
    version_id      BIGINT       NOT NULL,
    rule_name       VARCHAR(50)  NOT NULL,
    priority        INTEGER      NOT NULL CHECK (priority > 0),
    input_type      VARCHAR(10)  NOT NULL
                    CHECK (input_type IN ('TEXT', 'COLOR')),
    input_value     VARCHAR(100) NOT NULL,
    item_name       VARCHAR(100) NOT NULL,
    chute_id        BIGINT       NOT NULL,

    UNIQUE (version_id, priority),
    UNIQUE (version_id, input_type, input_value),
    UNIQUE (organization_id, belt_id, version_id, id, chute_id),
    FOREIGN KEY (organization_id, belt_id, version_id, chute_id)
        REFERENCES version_chutes
            (organization_id, belt_id, version_id, chute_id)
);

ALTER TABLE conveyor_belts
    ADD CONSTRAINT fk_belt_desired_version
    FOREIGN KEY (organization_id, id, desired_rule_version_id)
    REFERENCES rule_versions (organization_id, belt_id, id);

ALTER TABLE devices
    ADD CONSTRAINT fk_device_applied_version
    FOREIGN KEY (organization_id, belt_id, applied_rule_version_id)
    REFERENCES rule_versions (organization_id, belt_id, id);

-- 4. 분류 시도: v1에서는 DECISION을 받을 때 생성
CREATE TABLE sorting_attempts (
    attempt_id               UUID PRIMARY KEY,
    organization_id          BIGINT       NOT NULL,
    belt_id                  BIGINT       NOT NULL,
    device_id                UUID         NOT NULL,
    rule_version_id          BIGINT       NOT NULL,
    captured_at              TIMESTAMPTZ  NOT NULL,
    decided_at               TIMESTAMPTZ  NOT NULL,
    decision_status          VARCHAR(12)  NOT NULL
                             CHECK (decision_status IN
                                    ('MATCHED', 'UNMATCHED', 'ERROR')),
    decision_error_code      VARCHAR(50),
    discharge_status         VARCHAR(12)  NOT NULL DEFAULT 'UNCONFIRMED'
                             CHECK (discharge_status IN
                                    ('UNCONFIRMED', 'CONFIRMED', 'FAILED')),
    discharge_at             TIMESTAMPTZ,
    discharge_conflict       BOOLEAN      NOT NULL DEFAULT FALSE,
    recognized_input_type    VARCHAR(10)
                             CHECK (recognized_input_type IN ('TEXT', 'COLOR')),
    recognized_value         VARCHAR(100),
    rule_id                  BIGINT,
    chute_id                 BIGINT,       -- 규칙이 지정한 목적 슈트
    observed_chute_id        BIGINT,       -- 센서로 확인한 경우에만 기록
    group_name_snapshot     VARCHAR(100) NOT NULL,
    item_name_snapshot      VARCHAR(100),
    chute_name_snapshot     VARCHAR(50),
    image_uri               TEXT,
    created_at              TIMESTAMPTZ  NOT NULL DEFAULT now(),

    UNIQUE (organization_id, belt_id, device_id, attempt_id),
    FOREIGN KEY (organization_id, belt_id, device_id)
        REFERENCES devices (organization_id, belt_id, id),
    FOREIGN KEY (organization_id, belt_id, rule_version_id)
        REFERENCES rule_versions (organization_id, belt_id, id),
    FOREIGN KEY (
        organization_id, belt_id, rule_version_id, rule_id, chute_id
    )
        REFERENCES sorting_rules (
            organization_id, belt_id, version_id, id, chute_id
        ),
    FOREIGN KEY (organization_id, belt_id, observed_chute_id)
        REFERENCES chutes (organization_id, belt_id, id),

    CHECK (
        (recognized_input_type IS NULL AND recognized_value IS NULL)
        OR
        (recognized_input_type IS NOT NULL AND recognized_value IS NOT NULL)
    ),
    CHECK (
        (
            decision_status = 'MATCHED'
            AND rule_id IS NOT NULL
            AND chute_id IS NOT NULL
            AND recognized_input_type IS NOT NULL
            AND item_name_snapshot IS NOT NULL
            AND chute_name_snapshot IS NOT NULL
            AND decision_error_code IS NULL
        )
        OR
        (
            decision_status = 'UNMATCHED'
            AND rule_id IS NULL
            AND chute_id IS NULL
            AND item_name_snapshot IS NULL
            AND chute_name_snapshot IS NULL
            AND decision_error_code IS NULL
        )
        OR
        (
            decision_status = 'ERROR'
            AND rule_id IS NULL
            AND chute_id IS NULL
            AND item_name_snapshot IS NULL
            AND chute_name_snapshot IS NULL
            AND decision_error_code IS NOT NULL
        )
    ),
    CHECK (
        discharge_status = 'UNCONFIRMED'
        OR decision_status = 'MATCHED'
    ),
    CHECK (
        (
            discharge_status = 'UNCONFIRMED'
            AND discharge_at IS NULL
            AND observed_chute_id IS NULL
            AND discharge_conflict = FALSE
        )
        OR
        (
            discharge_status IN ('CONFIRMED', 'FAILED')
            AND discharge_at IS NOT NULL
        )
    )
);

-- 5. 장비가 보낸 개별 사건
CREATE TABLE device_events (
    event_id        UUID PRIMARY KEY,
    organization_id BIGINT      NOT NULL,
    belt_id         BIGINT      NOT NULL,
    device_id       UUID        NOT NULL,
    attempt_id      UUID,
    event_type      VARCHAR(24) NOT NULL
                    CHECK (event_type IN (
                        'DECISION',
                        'DISCHARGE_CONFIRMED',
                        'DISCHARGE_FAILED',
                        'DEVICE_ERROR'
                    )),
    error_code      VARCHAR(50),
    occurred_at     TIMESTAMPTZ NOT NULL,
    received_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    payload_sha256  CHAR(64)    NOT NULL
                    CHECK (payload_sha256 ~ '^[0-9a-f]{64}$'),
    image_sha256    CHAR(64)
                    CHECK (
                        image_sha256 IS NULL
                        OR image_sha256 ~ '^[0-9a-f]{64}$'
                    ),
    image_uri       TEXT,
    payload         JSONB       NOT NULL,

    UNIQUE (organization_id, event_id),
    FOREIGN KEY (organization_id, belt_id, device_id)
        REFERENCES devices (organization_id, belt_id, id),
    FOREIGN KEY (organization_id, belt_id, device_id, attempt_id)
        REFERENCES sorting_attempts
            (organization_id, belt_id, device_id, attempt_id),
    CHECK (
        (event_type = 'DECISION' AND attempt_id IS NOT NULL)
        OR
        (
            event_type = 'DISCHARGE_CONFIRMED'
            AND attempt_id IS NOT NULL
            AND error_code IS NULL
        )
        OR
        (
            event_type = 'DISCHARGE_FAILED'
            AND attempt_id IS NOT NULL
            AND error_code IS NOT NULL
        )
        OR
        (
            event_type = 'DEVICE_ERROR'
            AND error_code IS NOT NULL
        )
    )
);

CREATE UNIQUE INDEX uq_events_one_decision_per_attempt
    ON device_events (attempt_id)
    WHERE event_type = 'DECISION';

-- 6. 알림과 기존 인증 보조 테이블
CREATE TABLE user_notifications (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id   BIGINT      NOT NULL,
    event_id          UUID        NOT NULL,
    recipient_user_id BIGINT      NOT NULL,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    read_at           TIMESTAMPTZ,

    UNIQUE (event_id, recipient_user_id),
    FOREIGN KEY (organization_id, event_id)
        REFERENCES device_events (organization_id, event_id),
    FOREIGN KEY (organization_id, recipient_user_id)
        REFERENCES public.users (organization_id, id)
);



-- 7. 배포 후 변경 금지
CREATE FUNCTION guard_rule_version_row()
RETURNS trigger LANGUAGE plpgsql SET search_path = parcel, public AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        IF NEW.status <> 'DRAFT' THEN
            RAISE EXCEPTION '새 규칙 버전은 DRAFT로 생성해야 합니다';
        END IF;
        RETURN NEW;
    END IF;

    IF OLD.status = 'PUBLISHED' THEN
        RAISE EXCEPTION '배포된 규칙 버전은 변경하거나 삭제할 수 없습니다';
    END IF;

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;

    IF NEW.status = 'PUBLISHED' THEN
        NEW.published_at := now();
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_guard_rule_version_row
BEFORE INSERT OR UPDATE OR DELETE ON rule_versions
FOR EACH ROW EXECUTE FUNCTION guard_rule_version_row();

CREATE FUNCTION guard_rule_version_child()
RETURNS trigger LANGUAGE plpgsql SET search_path = parcel, public AS $$
DECLARE
    version_status VARCHAR(12);
BEGIN
    IF TG_OP IN ('UPDATE', 'DELETE') THEN
        SELECT status INTO version_status
        FROM rule_versions
        WHERE id = OLD.version_id
        FOR SHARE;

        IF version_status = 'PUBLISHED' THEN
            RAISE EXCEPTION '배포된 버전의 규칙·슈트 설정은 변경할 수 없습니다';
        END IF;
    END IF;

    IF TG_OP IN ('INSERT', 'UPDATE') THEN
        SELECT status INTO version_status
        FROM rule_versions
        WHERE id = NEW.version_id
        FOR SHARE;

        IF version_status = 'PUBLISHED' THEN
            RAISE EXCEPTION '배포된 버전에 규칙·슈트 설정을 추가할 수 없습니다';
        END IF;
    END IF;

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_guard_version_chutes
BEFORE INSERT OR UPDATE OR DELETE ON version_chutes
FOR EACH ROW EXECUTE FUNCTION guard_rule_version_child();

CREATE TRIGGER trg_guard_sorting_rules
BEFORE INSERT OR UPDATE OR DELETE ON sorting_rules
FOR EACH ROW EXECUTE FUNCTION guard_rule_version_child();

-- 벨트 지정·장비 적용·분류 시도에는 배포된 버전만 사용
CREATE FUNCTION assert_published_version(
    p_organization_id BIGINT,
    p_belt_id BIGINT,
    p_version_id BIGINT
)
RETURNS void LANGUAGE plpgsql SET search_path = parcel, public AS $$
DECLARE
    version_status VARCHAR(12);
BEGIN
    IF p_version_id IS NULL THEN
        RETURN;
    END IF;

    SELECT status INTO version_status
    FROM rule_versions
    WHERE organization_id = p_organization_id
      AND belt_id = p_belt_id
      AND id = p_version_id
    FOR SHARE;

    IF version_status IS DISTINCT FROM 'PUBLISHED' THEN
        RAISE EXCEPTION '배포된 규칙 버전만 지정할 수 있습니다';
    END IF;
END;
$$;

CREATE FUNCTION check_belt_desired_version()
RETURNS trigger LANGUAGE plpgsql SET search_path = parcel, public AS $$
BEGIN
    PERFORM assert_published_version(
        NEW.organization_id, NEW.id, NEW.desired_rule_version_id
    );
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_check_belt_desired_version
BEFORE UPDATE OF desired_rule_version_id ON conveyor_belts
FOR EACH ROW EXECUTE FUNCTION check_belt_desired_version();

CREATE FUNCTION check_device_applied_version()
RETURNS trigger LANGUAGE plpgsql SET search_path = parcel, public AS $$
BEGIN
    PERFORM assert_published_version(
        NEW.organization_id, NEW.belt_id, NEW.applied_rule_version_id
    );
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_check_device_applied_version
BEFORE INSERT OR UPDATE ON devices
FOR EACH ROW EXECUTE FUNCTION check_device_applied_version();

CREATE FUNCTION check_attempt_rule_version()
RETURNS trigger LANGUAGE plpgsql SET search_path = parcel, public AS $$
BEGIN
    PERFORM assert_published_version(
        NEW.organization_id, NEW.belt_id, NEW.rule_version_id
    );
    RETURN NEW;
END;
$$;

CREATE TRIGGER trg_check_attempt_rule_version_insert
BEFORE INSERT ON sorting_attempts
FOR EACH ROW EXECUTE FUNCTION check_attempt_rule_version();

CREATE TRIGGER trg_check_attempt_rule_version_update
BEFORE UPDATE OF organization_id, belt_id, rule_version_id
ON sorting_attempts
FOR EACH ROW EXECUTE FUNCTION check_attempt_rule_version();

-- 8. 기준 조회 인덱스
CREATE INDEX idx_attempts_org_time
    ON sorting_attempts
       (organization_id, captured_at DESC, attempt_id DESC);

CREATE INDEX idx_attempts_belt_time
    ON sorting_attempts
       (organization_id, belt_id, captured_at DESC, attempt_id DESC);

CREATE INDEX idx_events_attempt_time
    ON device_events (attempt_id, occurred_at);

CREATE INDEX idx_events_org_time
    ON device_events
       (organization_id, occurred_at DESC, event_id DESC);

CREATE INDEX idx_notifications_unread
    ON user_notifications (recipient_user_id, created_at DESC)
    WHERE read_at IS NULL;

ALTER TABLE sorting_attempts ADD CONSTRAINT ck_attempt_conflict_failed
    CHECK (NOT discharge_conflict OR discharge_status = 'FAILED');
CREATE TABLE event_images (
    event_id UUID PRIMARY KEY REFERENCES device_events(event_id),
    content_type VARCHAR(40) NOT NULL CHECK (content_type IN ('image/png','image/jpeg')),
    content BYTEA NOT NULL CHECK (octet_length(content) BETWEEN 1 AND 5242880)
);
-- Images and event metadata commit together; a failed transaction leaves neither behind.
