SET LOCAL search_path = parcel, public;

-- Preserve public history as legacy history: historical event/device/version IDs are unknown.
-- Import configuration as DRAFT only. Nothing is activated automatically.
CREATE TABLE migration_issues (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version_id BIGINT NOT NULL REFERENCES rule_versions(id),
    legacy_rule_id BIGINT NOT NULL,
    reason TEXT NOT NULL
);
INSERT INTO conveyor_belts(organization_id,code,name)
SELECT id,'LEGACY-1','Imported belt (review configuration before activation)' FROM organizations;

INSERT INTO sorting_groups(id,organization_id,belt_id,name)
SELECT g.id,u.organization_id,b.id,g.group_name || ' [legacy ' || g.id || ']'
FROM public.sorting_groups g JOIN public.users u ON u.id=g.manager_id
JOIN conveyor_belts b ON b.organization_id=u.organization_id AND b.code='LEGACY-1';
SELECT setval(pg_get_serial_sequence('parcel.sorting_groups','id'),COALESCE(max(id),1),max(id) IS NOT NULL) FROM sorting_groups;

INSERT INTO rule_versions(organization_id,belt_id,group_id,group_name_snapshot,version_no)
SELECT organization_id,belt_id,id,name,1 FROM sorting_groups;

INSERT INTO chutes(organization_id,belt_id,code,name)
SELECT DISTINCT g.organization_id,g.belt_id,'legacy-' || c.id,c.chute_name
FROM public.rule_chutes rc JOIN public.chutes c ON c.id=rc.chute_id
JOIN public.sorting_rules r ON r.id=rc.rule_id
JOIN sorting_groups g ON g.id=r.group_id;

INSERT INTO version_chutes(organization_id,belt_id,version_id,chute_id,chute_name_snapshot,servo_deg_snapshot)
SELECT DISTINCT v.organization_id,v.belt_id,v.id,c.id,old.chute_name,old.servo_deg
FROM public.sorting_rules r JOIN public.rule_chutes rc ON rc.rule_id=r.id
JOIN public.chutes old ON old.id=rc.chute_id
JOIN rule_versions v ON v.group_id=r.group_id
JOIN chutes c ON c.belt_id=v.belt_id AND c.code='legacy-' || old.id
WHERE old.servo_deg BETWEEN 0 AND 180;

INSERT INTO migration_issues(version_id,legacy_rule_id,reason)
SELECT v.id,r.id,'Missing/multiple chute, invalid angle, or duplicate normalized input: create a reviewed replacement version'
FROM public.sorting_rules r JOIN rule_versions v ON v.group_id=r.group_id
WHERE (SELECT count(*) FROM public.rule_chutes rc WHERE rc.rule_id=r.id) <> 1
   OR EXISTS (SELECT 1 FROM public.rule_chutes rc JOIN public.chutes c ON c.id=rc.chute_id
              WHERE rc.rule_id=r.id AND c.servo_deg NOT BETWEEN 0 AND 180)
   OR (SELECT count(*) FROM public.sorting_rules other WHERE other.group_id=r.group_id
       AND other.input_type=r.input_type AND upper(trim(other.input_value))=upper(trim(r.input_value))) <> 1;

INSERT INTO sorting_rules(organization_id,belt_id,version_id,rule_name,priority,input_type,input_value,item_name,chute_id)
SELECT v.organization_id,v.belt_id,v.id,r.rule_name,
       row_number() OVER (PARTITION BY v.id ORDER BY CASE WHEN r.input_type::text='TEXT' THEN 0 ELSE 1 END,r.id),
       r.input_type::text,upper(trim(r.input_value)),r.item_name,c.id
FROM public.sorting_rules r JOIN public.rule_chutes rc ON rc.rule_id=r.id
JOIN rule_versions v ON v.group_id=r.group_id
JOIN chutes c ON c.belt_id=v.belt_id AND c.code='legacy-' || rc.chute_id
WHERE NOT EXISTS (SELECT 1 FROM migration_issues i WHERE i.legacy_rule_id=r.id);
